FROM php:7.4-cli
WORKDIR /home/administrador/Practica2_DevSecOps/Docker/Docker1
COPY /home/administrador/Practica2_DevSecOps/index.php /var/www/html/index.php
CMD ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html" ]

