FROM ubuntu:latest
WORKDIR /home/administrador/Practica2_DevSecOps
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN apt-get install apache2 git
RUN apt-get install php
EXPOSE 80
WORKDIR /var/www/html
RUN git clone https://github.com/drnic/php-helloworld.git
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
